// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";

import './Dropdown.scss';
;

function setSelected(param) {
  console.log("");
  
}

var context = React.createContext([
      undefined,
      setSelected
    ]);

var provider = context.Provider;

function Dropdown$Context$Provider(Props) {
  var value = Props.value;
  var children = Props.children;
  return React.createElement(provider, {
              value: value,
              children: children
            });
}

var Provider = {
  provider: provider,
  make: Dropdown$Context$Provider
};

var Context = {
  selected: undefined,
  setSelected: setSelected,
  context: context,
  Provider: Provider
};

function Dropdown(Props) {
  var selectedValue = Props.selectedValue;
  var selectValue = Props.selectValue;
  var children = Props.children;
  return React.createElement(Dropdown$Context$Provider, {
              value: [
                selectedValue,
                selectValue
              ],
              children: null
            }, Belt_Option.getWithDefault(Belt_Option.map(selectedValue, (function (prim) {
                        return String(prim);
                      })), "select value"), children);
}

function Dropdown$Option(Props) {
  var value = Props.value;
  var children = Props.children;
  var match = React.useContext(context);
  var selectValue = match[1];
  return React.createElement("div", {
              className: "app-dropdown-option",
              onClick: (function (param) {
                  return Curry._1(selectValue, value);
                })
            }, children);
}

var $$Option = {
  make: Dropdown$Option
};

var make = Dropdown;

export {
  Context ,
  make ,
  $$Option ,
  
}
/*  Not a pure module */
