// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as React from "react";
import * as Dropdown$Dropdown from "./components/Dropdown.bs.js";

import './App.scss';
;

function App(Props) {
  var match = React.useState(function () {
        
      });
  var setSelectedValue = match[1];
  var selectValue = function (value) {
    return Curry._1(setSelectedValue, (function (param) {
                  return value;
                }));
  };
  return React.createElement("div", {
              className: "app-container"
            }, React.createElement(Dropdown$Dropdown.make, {
                  selectedValue: match[0],
                  selectValue: selectValue,
                  children: null
                }, React.createElement(Dropdown$Dropdown.$$Option.make, {
                      value: 0,
                      children: "Value 1"
                    }), React.createElement(Dropdown$Dropdown.$$Option.make, {
                      value: 1,
                      children: "Value 2"
                    }), React.createElement(Dropdown$Dropdown.$$Option.make, {
                      value: 2,
                      children: "Value 3"
                    })));
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
